
development:
  adapter: mysql2
  encoding: utf8
  database: smellpgh_dev
  username: plaintext_username_here
  password: abc123

production:
  adapter: mysql2
  encoding: utf8
  database: smellpgh_production
  username: plaintext_username_here
  password: plaintext_password_here

